import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { inter, lora, playfairDisplay, roboto } from "@/lib/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${lora.className} ${roboto.className} ${playfairDisplay.className} antialiased flex flex-col min-h-screen`}>
        <NavigationBar />
        <main className="flex-grow">
          <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            {children}
          </div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
